### ISSUE TITLE
Assertion error on SIGINT

### ISSUE THREAD

**Issue by Bondza** [hmalphettes/log4js-elasticsearch#2]
I added a listener for uncaughtException and found that log4js-elasticsearch cause an assertion error on SIGINT.

This is the trace:
Error: assertion error
    at process.assert (node.js:299:21)
    at process.removeListener (node.js:779:9)
    at clearProcessListeners (/Users/Bondza/Sprinkle/Git/track/node_modules/log4js-elasticsearch/lib/elasticsearch-bulk.js:163:13)
    at process.onProcessSigint (/Users/Bondza/Sprinkle/Git/track/node_modules/log4js-elasticsearch/lib/elasticsearch-bulk.js:141:3)
    at process.g (events.js:180:16)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)

I had a quick look at the code from elasticsearch-bulk.js. The error seems inevitable on either SIGINT or exit, because the listeners are setup using process.once which will remove the listener after the signal was received. Which results in the error above when trying to remove both listeners.

**Comment by hmalphettes** [comment]
Fixed here: https://github.com/hmalphettes/log4js-elasticsearch/pull/3
